const messageConstant = {
    SUCCESS: 'Success',
    ERROR: 'Error',
    LOGIN_FAILED: 'Username or Password is invalid',
    ACCESS_DENIED: 'Access denied...',
    INTERNAL_SERVER_ERROR: 'Internal server error',
    USER_CREATED: 'User created successfully',
    USER_CREATION_FAILED: 'User creation failed',
    USER_DELETED: 'User deleted successfully.',
    USER_NOT_EXIST: 'User not exist on this email',
    USER_ALREADY_EXISTS: 'User already exists',
    POST_CREATED: 'Post created successfully',
    POST_RETRIEVED: 'Post retrieved successfully',
    POST_UPDATED: 'Post updated successfully',
    POST_DELETED: 'Post deleted successfully',
    POST_NOT_FOUND: 'Post not found',
    BAD_REQUEST: 'Bad request',
    EMAIL_IN_USED: 'Email already in used',
    IMAGE_NOT_UPLOADED: 'Upload the image',
    FILE_NOT_UPLOADED:
        'Please Upload the file with valid extension(.pdf, .png, .jpg, .jpeg)',
    FILE_UPLOADED: 'File uploaded Successfully',
    FILE_DOWNLOADED: 'File downloaded successfully.',
    WRONG_PASSWORD: 'Wrong password',
    NOT_AUTHORIZED: 'Not authorized',
    USER_HAVE_3_POSTS: 'User have more than 3 posts',
    RESET_EMAIL_SENT: 'Reset email sent successfully',
    RESET_EMAIL_FAILED: 'Reset email failed',
    PASSWORD_RESET: 'Password reset successfully',
    INVALID_RESET_TOKEN: 'Invalid or expired Token',
    EMAIL_NOT_MATCH: 'Email and Confirm Email are not the same',
    PASSWORD_NOT_MATCH: 'Password and Confirm Password are not the same',
    NOT_GET_HASHED_TOKEN: 'Hashed token cannot get, please try again',
    REQUEST_CREATED: 'Request Created Successfully.',
    REQUEST_DELETED: 'Request Deleted Successfully.',
    NO_FILE_SELECTED: 'File not selected.',
    FILE_NOT_FOUND: 'File not found',
    FILE_DELETED: 'File deleted successfully.',
    ERROR_DOWNLOAD_FILE: 'Error when downloading file',
    ERROR_UPLOAD_FILE: 'Error when uploading file',
    MESSAGE_SENT_SUCCESSFULLY: 'Message sent successfully',
    ERROR_SEND_MESSAGE: 'Error while sending message',
    ROLE_CREATED: 'Role created successfully',
    ROLE_ALREADY_EXISTS: 'Role already exists',
    ROLE_RETRIEVED: 'Role retrieved successfully.',
    ROLE_NOT_FOUND: 'Role not found',
    ROLE_UPDATED: 'Role updated successfully.',
    ROLE_DELETED: 'Role deleted successfully',
    REQUEST_EMAIL_SMS_SENT: 'Request email and sms sent successfully',
    EMAIL_SENT: 'Email sent successfully.',
    MISSING_SECTION_OR_UPDATED_DATA: 'Missing section or updates data',
    UPDATE_FAILED: 'Update failed...',
    AGREEMENT_EMAIL_SENT: 'Agreement email sent successfully',
    INVALID_SORT_PARAMETER: 'Invalid sort parameter...',
    BUSINESS_ALREADY_EXISTS: 'Your business already exists in platform.',
    BUSINESS_UPDATED: 'Business updated successfully.',
    BUSINESS_DELETED: 'Business deleted successfully.',
    DATA_NOT_FOUND: 'Data not found...',
    INVALID_BODY: 'Invalid body parameters.',
    CURRENT_PASSWORD_WRONG:
        'Your current password is wrong, enter the correct password',
    SHIFT_CREATION_FAILED: 'Shift Creation failed...',
    SHIFT_CREATED: 'Shift Created Successfully.',
    SHIFT_RETRIEVED: 'Shifts Retrieved Successfully.',
    SHIFT_APPROVED: 'Shifts Approved Successfully.',
    SHIFT_DELETED: 'Shifts Deleted Successfully.',
    INVALID_REGION:
        'Invalid region. Please select from following ( Maryland, Virginia, District of Columbia, New York )',
    VALID_REGION: 'Valid Region.',
    INVALID_INPUT: 'Invalid file names array.',
    NOTIFICATION_UPDATED: 'Notification Updated Successfully.',
    PATIENT_UNBLOCK: 'Patient unblock successfully.',
    EMAIL_LOG_RETRIEVED: 'Email log retrieved successfully.',
    SMS_LOG_RETRIEVED: 'SMS log retrieved successfully.',
    VENDOR_RETRIEVED: 'Vendor retrieved successfully.'
};

export default messageConstant;
