const messageConstant = {
    SUCCESS: 'Success',
    ERROR: 'Error',
    LOGIN_FAILED: 'Username or Password is invalid',
    ACCESS_DENIED: 'Access denied...',
    INTERNAL_SERVER_ERROR: 'Internal server error',
    USER_CREATED: 'User created successfully',
    USER_CREATION_FAILED: 'User creation failed',
    USER_NOT_EXIST: 'User not exist on this email',
    USER_ALREADY_EXISTS: 'User already exists',
    POST_CREATED: 'Post created successfully',
    POST_RETRIEVED: 'Post retrieved successfully',
    POST_UPDATED: 'Post updated successfully',
    POST_DELETED: 'Post deleted successfully',
    POST_NOT_FOUND: 'Post not found',
    BAD_REQUEST: 'Bad request',
    EMAIL_IN_USED: 'Email already in used',
    IMAGE_NOT_UPLOADED: 'Upload the image',
    FILE_NOT_UPLOADED:
        'Please Upload the file with valid extension(.pdf, .png, .jpg, .jpeg)',
    FILE_UPLOADED: 'File uploaded Successfully',
    WRONG_PASSWORD: 'Wrong password',
    NOT_AUTHORIZED: 'Not authorized',
    USER_HAVE_3_POSTS: 'User have more than 3 posts',
    RESET_EMAIL_SENT: 'Reset email sent successfully',
    RESET_EMAIL_FAILED: 'Reset email failed',
    PASSWORD_RESET: 'Password reset successfully',
    INVALID_RESET_TOKEN: 'Invalid or expired Token',
    PASSWORD_NOT_MATCH: 'Password and Confirm Password are not the same',
    NOT_GET_HASHED_TOKEN: 'Hashed token cannot get, please try again',
    REQUEST_CREATED: 'Request Created Successfully',
    FILE_NOT_FOUND: 'File not found',
    ERROR_DOWNLOAD_FILE: 'Error when downloading file',
    ERROR_UPLOAD_FILE: 'Error when uploading file',
    MESSAGE_SENT_SUCCESSFULLY: 'Message sent successfully',
    ERROR_SEND_MESSAGE: 'Error while sending message',
    ROLE_ALREADY_EXISTS: 'Role already exists',
    REQUEST_EMAIL_SMS_SENT: 'Request email and sms sent successfully',
    MISSING_SECTION_OR_UPDATED_DATA: 'Missing section or updates data',
    UPDATE_FAILED: 'Update failed...',
    AGREEMENT_EMAIL_SENT: 'Agreement email sent successfully',
    INVALID_SORT_PARAMETER: 'Invalid sort parameter...',
    BUSINESS_ALREADY_EXISTS: 'Your business already exists in platform.',
    DATA_NOT_FOUND: 'Data not found...',
    INVALID_BODY: 'Invalid body parameters.',
    SHIFT_CREATION_FAILED: "Shift Creation failed..."
};

export default messageConstant;
